language: node_js

node_js:
  - "6"

env:
  global:
  - PnPTesting_ClientId="ClientIdValue"
  - PnPTesting_ClientSecret="ClientSecretValue"
  - PnPTesting_SiteUrl="SiteUrlValue"
  - PnPTesting_NotificationUrl="NotificationUrlValue"

before_script:
  - npm install -g gulp

script: gulp test:travis