language: node_js

node_js:
  - "6"

before_script:
  - npm install -g gulp

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then gulp package; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then gulp test:travis; fi'